import type { SeriesTheme } from '../../types/series-theme'

export const SERIES_THEMES: Record<string, SeriesTheme> = {
  qinghua: {
    id: 'qinghua',
    name: '青花瓷',
    primary: '#87CEEB',
    soft: 'rgba(135, 206, 235, 0.2)',
    bgGradient: 'linear-gradient(180deg, #0a1f3d 0%, #1E4D8C 50%, #0a1f3d 100%)',
    particle: 'sparkle',
    decoration: 'splash',
    cardBorder: 'soft',
    textGlow: true,
  },
  shanjing: {
    id: 'shanjing',
    name: '山海经',
    primary: '#C41E3A',
    soft: 'rgba(196, 30, 58, 0.2)',
    bgGradient: 'radial-gradient(ellipse at center, #2a0a0a 0%, #0a0505 100%)',
    particle: 'mist',
    decoration: 'seal',
    cardBorder: 'ink-line',
    textGlow: true,
    shader: 'fluid',
  },
  dragon: {
    id: 'dragon',
    name: '团龙',
    primary: '#D4AF6A',
    soft: 'rgba(212, 175, 106, 0.2)',
    bgGradient: 'linear-gradient(135deg, #2A0808 0%, #5a1010 50%, #2A0808 100%)',
    particle: 'cloud',
    decoration: 'seal',
    cardBorder: 'gold-line',
    textGlow: true,
    silkCanvas: true,
  },
  taotie: {
    id: 'taotie',
    name: '饕餮',
    primary: '#8B7355',
    soft: 'rgba(139, 115, 85, 0.2)',
    bgGradient: 'radial-gradient(ellipse at center, #1a2818 0%, #0a0f08 100%)',
    particle: 'rust',
    decoration: 'bronze',
    cardBorder: 'soft',
    textGlow: false,
  },
  scroll: {
    id: 'scroll',
    name: '唐草',
    primary: '#98FB98',
    soft: 'rgba(152, 251, 152, 0.2)',
    bgGradient: 'linear-gradient(135deg, #0f1a08 0%, #1f2a10 50%, #0f1a08 100%)',
    particle: 'growth',
    decoration: 'vine',
    cardBorder: 'soft',
    textGlow: false,
  },
  cloud: {
    id: 'cloud',
    name: '云纹',
    primary: '#B0E0E6',
    soft: 'rgba(176, 224, 230, 0.2)',
    bgGradient: 'linear-gradient(180deg, #0a1a2a 0%, #1a2f3f 50%, #0a1a2a 100%)',
    particle: 'cloud',
    decoration: 'cloud',
    cardBorder: 'soft',
    textGlow: false,
    shader: 'cloud',
  },
  floral: {
    id: 'floral',
    name: '花卉',
    primary: '#FFB6C1',
    soft: 'rgba(255, 182, 193, 0.2)',
    bgGradient: 'linear-gradient(180deg, #2a1a1f 0%, #1a0f10 100%)',
    particle: 'sparkle',
    decoration: 'splash',
    cardBorder: 'soft',
    textGlow: false,
  },
  geometric: {
    id: 'geometric',
    name: '几何',
    primary: '#DDA0DD',
    soft: 'rgba(221, 160, 221, 0.2)',
    bgGradient: 'linear-gradient(180deg, #1a0f1f 0%, #0f0810 100%)',
    particle: 'none',
    decoration: 'none',
    cardBorder: 'ink-line',
    textGlow: false,
  },
  corner: {
    id: 'corner',
    name: '角花',
    primary: '#F0E68C',
    soft: 'rgba(240, 230, 140, 0.2)',
    bgGradient: 'linear-gradient(180deg, #1f1f0a 0%, #0f0f08 100%)',
    particle: 'none',
    decoration: 'splash',
    cardBorder: 'gold-line',
    textGlow: false,
  },
  tile: {
    id: 'tile',
    name: '四方连续',
    primary: '#B0C4DE',
    soft: 'rgba(176, 196, 222, 0.2)',
    bgGradient: 'linear-gradient(180deg, #0a0f1a 0%, #1a1f2a 100%)',
    particle: 'none',
    decoration: 'none',
    cardBorder: 'soft',
    textGlow: false,
  },
  ai: {
    id: 'ai',
    name: 'AI 元素库',
    primary: '#9b59b6',
    soft: 'rgba(155, 89, 182, 0.2)',
    bgGradient: 'linear-gradient(180deg, #1a0a2a 0%, #0f051a 100%)',
    particle: 'sparkle',
    decoration: 'none',
    cardBorder: 'soft',
    textGlow: true,
  },
  neutral: {
    id: 'neutral',
    name: '中性',
    primary: '#D4AF6A',
    soft: 'rgba(212, 175, 106, 0.15)',
    bgGradient: 'var(--color-bg-base)',
    particle: 'none',
    decoration: 'none',
    cardBorder: 'soft',
    textGlow: false,
  },
}

export function getSeriesTheme(id: string): SeriesTheme {
  return SERIES_THEMES[id] ?? SERIES_THEMES.neutral
}
